from typing import Any, Protocol


class StorageClient(Protocol):
    def presign_put(self, key: str, content_type: str, ttl_seconds: int) -> str: ...
    def presign_get(self, key: str, ttl_seconds: int) -> str: ...
    def head(self, key: str) -> bool: ...
    def ping(self) -> bool: ...


class QueueClient(Protocol):
    def enqueue(self, message: dict) -> None: ...
    def ping(self) -> bool: ...


class JobsRepository(Protocol):
    def create_job(
        self, job_id: str, input_key: str, variants: list[dict[str, Any]]
    ) -> None: ...
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def update_status(
        self, job_id: str, status: Any, error: str | None = None
    ) -> bool: ...
    def update_variant(
        self,
        job_id: str,
        variant_name: str,
        status: Any,
        output_key: str | None = None,
        error: str | None = None,
    ) -> bool: ...
    def ping(self) -> bool: ...
